name: Solace Intelligence Evolution V2

# This GitHub Actions workflow will automate the evolution of the Solace Intelligence Model.

on workflow_dispatch:
  jobs:

    - name: Run Intelligence Evolution
      run: python3 -m advanced_learning_model.py

schedule:
  daily:
    - name: Run Self-Learning Cycle
      run: python3 -m advanced_learning_model.py

workflow_dispatch:
  type: workflow_dispatch

events:
  workflow_dispatch: }