name: Update Workflow

on workflow_dispatch:
  jobs:

    - name: Update intelligence workflow file
      run: python3 -m update_script.py

schedule:
  daily:
    - name: Check and update workflow file
      run: python3 -m update_script.py

workflow_dispatch:
  type: workflow_dispatch

events:
  workflow_dispatch:
    type: workflow_dispatch
  workflow_dispatch: